### ISSUE TITLE
Release 1.8.2?

### ISSUE THREAD

**Issue by tomcashman** [libgdx/gdx-ai#108]
Just wondering if there is a plan to release 1.8.2 soon? Are there any outstanding issues blocking this?

**Comment by davebaol** [comment]
No, no special reason apart from my rare spare time.
In the next few days I'm going to update dependencies and release a minor version.

**Comment by tomcashman** [comment]
Would it be possible to release it depending on libgdx 1.9.8 as per the current snapshot?

**Comment by davebaol** [comment]
Well, yes! But why?

Also, damn.... this is embarrassing! 😞 
I think I need your help. Too many time I don't work on gdx-ai and intellij  idea.
I cannot get tests projects working correctly.
Cannot find assets. At runtime I get `Error reading file: data/uiskin.json`
Any idea how to fix this into the ide.

**Comment by tomcashman** [comment]
I'm in the middle of a project for my publisher and I had a lot of problems upgrading to libgdx 1.9.9 and haven't had a chance to see if 1.9.10 fixed the issues 😛 

In IntelliJ you can right-click the project and go to Module Settings then mark a folder as a resource directory (I think).

**Comment by davebaol** [comment]
Ok, I found it! Thanks 😃

**Comment by davebaol** [comment]
Version 1.8.2 just released

**Comment by tomcashman** [comment]
Thank you :)
