### ISSUE TITLE
MessageDispatcher shouldn't be a Singleton

### ISSUE THREAD

**Issue by niyaro** [libgdx/gdx-ai#20]
MessageDispatcher doesn't work with system resources so making it a Singleton is an anti-pattern, since it heavily limits it's usage.
http://stackoverflow.com/questions/137975/what-is-so-bad-about-singletons

It makes perfect sense, for example, to have separate MessageDispatchers for different parts of the app - one for ui, other one for ai - cause that makes message constants easier to maintain as they aren't clutter together, and it makes it possible to configure time granularity differently for different dispatchers.

**Comment by PhannGor** [comment]
Another reason, at least for current implementation, is that there is no possibility to extend **MessageDispatcher** because of private constructor.

**Comment by davebaol** [comment]
Of course `MessageDispatcher` would have public cunstructor if we move singleton capability to `MessageManager` :)

**Comment by davebaol** [comment]
@niyaro @PhannGor 
Finally done!
Better late than never  :smile:

**Comment by PhannGor** [comment]
@davebaol 
Cool, thanks!
