### ISSUE TITLE
Add BehaviorTree.reset() Method

### ISSUE THREAD

**Issue by chrisapril** [libgdx/gdx-ai#26]
Hi!

In my program i am interrupting the execution from BehaviorTree while they are running. After that i want to reuse the BehaviorTree instance (or pool it). 

At the moment im am interating through the nodes of the tree with this method:

````java
	@SuppressWarnings("rawtypes")
	private void reset(Task<?> task) {

		if (!ClassReflection.isInstance(Sequence.class, task) && !ClassReflection.isInstance(Decorator.class, task)
				&& !ClassReflection.isInstance(BranchTask.class, task))
			task.childRunning(null, null);

		if (task instanceof Poolable)
			((Poolable) task).reset();

		for (int i = 0; i < task.getChildCount(); i++) {
			Task child = task.getChild(i);
			reset(child);
		}
	}
````

At the moment i am abusing the childRunning() method to set the runningTask to null. But i had to add the checks to not get a nullpointer when calling childRunning().

Is there a better way to reset a BehaviorTree or can you provide a method to do this?

**Comment by davebaol** [comment]
Yeah I can add a reset method to the `Task` superclass.
`myTree.reset()` will reset all its children up to leaf tasks, but I think the `Poolable` part will be developer's responsibility.
Actually, I think you'd better pool whole trees of the same type, rather than individual tasks.
What do you think?

**Comment by chrisapril** [comment]
Yes, at the moment i am pooling the whole tree. When the tree is pooled, i am resetting the leaf tasks with:

if (task instanceof Poolable)
        ((Poolable) task).reset();


To reset a behavior tree you have to set runningTask = null in all task leafs and actualTask = 0 in BranchTask, is it right?

**Comment by davebaol** [comment]
Correct. Even `Parallel` must override the `reset` method.
Let me know if this is enough for your needs.

**Comment by chrisapril** [comment]
Thanks, its perfect!

**Comment by davebaol** [comment]
Glad to hear it :smile:
