### ISSUE TITLE
Going beyond running the tests

### ISSUE THREAD

**Issue by alex-place** [libgdx/gdx-ai#27]
So I really like what where the AI extension stands and would love to try some features out. However it seems to me like there is no documentation beyond the tests on how someone would implement something like say a steering behavior. It's nearly impossible for me to pull working code to demo in a new project from the tests. How would I set up say a simple LookWhereYourGoingTest in a new libgdx project? I'm sorry if I am missing something really obvious just need some help.

**Comment by davebaol** [comment]
Short answer:

* add gdx-ai dependency to your project
* take a character in your game and let it implement the Steerable interface, something like https://github.com/libgdx/gdx-ai/wiki/Steering-Behaviors#the-steering-system-api
* add a steering behavior (or a composition of steering behaviors) to the character
* on each frame call its update method and render it

If you have more specific questions I'll be glad to answer. :smile:

**Comment by davebaol** [comment]
I've just realized you're are one of the guys behind [this initiative](http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=18181).
I've no time to join the game jam, sorry, but I'll look into the code if you have problems. Just let me know. :wink:

**Comment by alex-place** [comment]
Ok gonna give it a shot in the morning. Would like to use this with Ashley unless you think thats a bad idea. I'll let you know if I have any problems.

**Comment by alex-place** [comment]
I figured out implementing Steering behaviors. It's much easier than one would think. Feel free to close this but consider making a quick how to for such things. I would do it myself but I'm in a bit of a time crunch.

**Comment by davebaol** [comment]
Glad you figured it out.
