### ISSUE TITLE
Allow dispatching messages without the need of a Telegraph

### ISSUE THREAD

**Issue by nfantone** [libgdx/gdx-ai#28]
Right now, sending a message using the `MessageDispatcher#dispatchMessage()` method requires specifying a `sender`, which is an instance of `Telegraph`.

A **very** common case scenario is implementing the interface on the very same class you are dispatching the message from. So, typically, you end up with something like:

```java
MessageManager.getInstance().dispatchMessage(this, 1);
```

Equally common is having classes that only **generate** events and do not handle any type of message. Currently, those classes are forced to implement `Telegraph` in order to broadcast events (or to have access to some other unnecessary `Telegraph` instance). So, you find yourself writing this

```java
	@Override
	public boolean handleMessage(final Telegram msg) {
		return false;
	}
```

very frequently, just to **dispatch** a message. I tend to think the API could benefit from removing the need of having a mandatory `sender` parameter. If you do not specify one, just dispatch the message to every possible recipient from an _anonymous_ sender.

What do you think?

**Comment by davebaol** [comment]
> Currently, those classes are forced to implement `Telegraph` in order to broadcast events (or to have access to some other unnecessary `Telegraph` instance).

Can't check right now., does it work if you pass a `null` sender? Not sure, `(Telegraph)null` might be needed.
If it works then you don't have to implement `Telegraph`, but yes an overloaded `dispatchMessage` without the sender argument might be useful.

**Comment by nfantone** [comment]
> does it work if you pass a null sender? Not sure, (Telegraph)null might be needed.

It **does** work, indeed! But then you might want to fix some debug logs in `MessageDispatcher` like

```java
Gdx.app.log(LOG_TAG, "Instant telegram dispatched at time: " + currentTime + " by " + sender + " for " + receiver + ". Msg is " + msg);
```

To avoid logging a `null` string (if it is bothersome). That's the only drawback I could find.

**Comment by davebaol** [comment]
Done!
The sender will be logged as a null string just like it happens with the receiver. :wink:

**Comment by nfantone** [comment]
Great! Thanks for the fast response and work.
