### ISSUE TITLE
Support for selectable pathdining on custom node types

### ISSUE THREAD

**Issue by piotr-j** [libgdx/gdx-ai#29]
Id like to start discussion about this topic, that im not even sure how to title correctly. 
Take for example the [pfa tests](https://github.com/libgdx/gdx-ai/tree/master/tests/src/com/badlogic/gdx/ai/tests/pfa). We have `TiledNodes` of certain types. We pathfind on `TILE_FLOOR`. What if we want have units that can only walk on `TILE_WALL` or on both? 
What would be optimal way of implementing ability to select on what we pathfind? Should something like this even be supported by the library, or should it be left to the user to implement?

**Comment by piotr-j** [comment]
I've finally got to integrating the path finding today. Surprisingly simple to replace my own implementation with this one. To solve the problem i set the mover in the graph before i start the search. I use it to filter connections from nodes. I also use it to calculate the cost in the connection. However, this probably wont work with time slicing. Got to tackle that next. Also hierarchical. 

Anybody got better idea how to implement this?

**Comment by davebaol** [comment]
Nice. :smile: 
Why do you think that it won't work with time slicing?

**Comment by piotr-j** [comment]
I had some problems adapting the stuff from test to my stuff. The abuse of Telegrams was a little annoying to figure out. It probably should use proper message id and status check instead of using instance check and just freeing stuff. In my case, the enclosing class gets the event before the queue. 
In the end it took like 15 minutes. Ive added the stuff i need to the request and it works fine. 
Next, implement the hierarchical stuff with quad tree. Will be fun.
Heres a ss of qt view: 
 ![Quad tree view](http://i.imgur.com/fwMkFsb.jpg)
Some paths are visible as well, with new pf the cost or something is broken and they are far from ideal.

**Comment by davebaol** [comment]
> The abuse of Telegrams was a little annoying to figure out.

Yeah interruptible pathfinding is not documented yet, sorry. 

> It probably should use proper message id and status check instead of using instance check and just freeing stuff.

I guess you're talking about the method `InterruptibleFlatTiledAStarTest#handleMessage`.
Sure, in a real game you should check the message code. However the request status should always be `SEARCH_FINALIZED` when you receive the telegram.

> In my case, the enclosing class gets the event before the queue. 

Hmmm.. not sure to understand. :confused:

**Comment by piotr-j** [comment]
I understand now why I had problems. Ive registered for the event as usual, while the request controls calls the sender directly. Since Ive registered before the control, without the check the request for freed before it was processed. That caused various npes. I still think that the event should be handled in clearer way in the test. I can submit PR if you want.

**Comment by davebaol** [comment]
PR welcome :wink:

**Comment by davebaol** [comment]
PR merged, thanks.

About the original problem, were you able to easily solve it in your code?
If so, I think we can close this.

**Comment by piotr-j** [comment]
It was easy enough. Close it.
