### ISSUE TITLE
FSM: provide implementation of StateMachine with the "strict" change of state

### ISSUE THREAD

**Issue by PhannGor** [libgdx/gdx-ai#32]
It is common case scenario when you want to trigger state change only if current state is different than new one:

```java
if (!mStateMachine.isInState(PlayerState.RUN)) {
    mStateMachine.changeState(PlayerState.RUN);
}
```

What's about to add some default implementaion of the state machine with this check to be available out of the box? Something like this:

```java
public class StrictStateMachine<E> extends DefaultStateMachine<E> {

    /**
     * @see DefaultStateMachine#DefaultStateMachine(E)
     */
     public StrictStateMachine(E owner) {
        super(owner, null, null);
    }

    /**
     * @see DefaultStateMachine#DefaultStateMachine(E, State)
     */
    public StrictStateMachine(E owner, State<E> initialState) {
        super(owner, initialState, null);
    }

    /**
     * @see DefaultStateMachine#DefaultStateMachine(E, State, State)
     */
    public StrictStateMachine(E owner, State<E> initialState, State<E> globalState) {
        super(owner, initialState, globalState);
    }

    @Override
    public void changeState(State<E> newState) {
        if (!isInState(newState)) {
            super.changeState(newState);
        }
    }
}
```

**Comment by davebaol** [comment]
I'd prefer to leave such a thing to developer's responsibility for these reasons:
- usually in a FSM you want to block reentering only for some states, not for all
- in case you need such a functionality the implementation is really simple 
- for consistency we should provide the same functionality for the StackStateMachine

**Comment by PhannGor** [comment]
Sounds reasonable and i agree that implementation is quite simple if someone need it.

Closing issue.
