### ISSUE TITLE
Arrive doesn't arrive with velocity 0 and always turn in the end whatever parameter you choose

### ISSUE THREAD

**Issue by atollFP** [libgdx/gdx-ai#33]
You can reproduce in the tests, you will see that the sprite will turn instead of facing the direction he had when he arrived. I tested with different parameters.

**Comment by davebaol** [comment]
Believe me, It's just a matter of parameter tweaking and rounding errors due to floating point math.
Try to tweak timeToTarget and tolerance to minimize that effect, you probably have to decrease both. Often you definitely solve the issue like that. When it doesn't happen you can disable the arrive behavior once the steerable has arrived to the target.

**Comment by atollFP** [comment]
Would it be possible to use another numeric type without those floating errors ? I have really tried a lot of combination of parameters and it never disappear and when it does it's never consistent. It depend of the speed you're coming from.

**Comment by davebaol** [comment]
Yeah double should help to minimize the issue.
Try copying Arrive to DoubleArrive, replace float with double and let me know. :smile:

**Comment by davebaol** [comment]
Oh no, I just realized that most of the math is in the code that updates position, velocity, orientation and accelerations. And of course that code is out of behavior classes.

**Comment by atollFP** [comment]
Ok, I will do that. The sad part is that most of libgdx is in float so I will have to convert from Double to Float when updating the sprite position.

**Comment by davebaol** [comment]
Why don't you just disable arrive when you're on target?

**Comment by atollFP** [comment]
Would you implement that in applySteering ?

**Comment by davebaol** [comment]
At line https://github.com/libgdx/gdx-ai/blob/master/tests/src/com/badlogic/gdx/ai/tests/steer/scene2d/SteeringActor.java#L236 replace `MathUtils.FLOAT_ROUNDING_ERROR`, whose value is 0.000001f,
with 0.001f.
There you go! Now scene2d arrive stops on target.
As I told you, it's just a matter of tweaking parameters. Actually, updating orientation to the direction of motion with a certain tolerance on 0 velocity is just one of them. :wink:

**Comment by atollFP** [comment]
So what I intended to do is to have my ships facing the direction they're going. Either I use independant facing with Arrive coupled to LookWhereYouAreGoing and I have the problem described above (your fix only apply to non independant facing), either I use independant facing but then I get infinite angular speed when velocity is 0. This is not very realist for a ship. I'm not sure if it's the expected behavior either. Shouldn't a Steerable do a big U-Turn when they are oriented the opposite of where they want to go when they have non independant facing behavior ?

**Comment by atollFP** [comment]
There is a way to fix it. Apply the same fix than you did to the LookWhereYouAreGoing behavior:

https://github.com/libgdx/gdx-ai/blob/master/gdx-ai/src/com/badlogic/gdx/ai/steer/behaviors/LookWhereYouAreGoing.java

I think that would work and solve my issue.

**Comment by atollFP** [comment]
I edited my local version of gdx-ai to fix LookWhereYouAreGoing and it solved my issue :)

**Comment by davebaol** [comment]
> I edited my local version of gdx-ai to fix LookWhereYouAreGoing and it solved my issue :)

Ok thanks. Added that threshold to the Limiter interface.


> Shouldn't a Steerable do a big U-Turn when they are oriented the opposite of where they want to go when they have non independant facing behavior ?

U-Turn, J-Turn and similar maneuvers require motor control techniques.
