### ISSUE TITLE
Circle formation of 1 element fails

### ISSUE THREAD

**Issue by atollFP** [libgdx/gdx-ai#34]
Hi, because of the way radius is calculated in CirclePattern:

`float radius = memberRadius / (float)Math.sin(Math.PI / numberOfSlots);`

it get divided by 0 if there is only 1 slot. We should be able to generalize formation even for 1 slot only.

**Comment by davebaol** [comment]
Done!
Thanks

**Comment by atollFP** [comment]
No problem. The Formation Motion you added recently is awesome, well thought and exactly what I needed. I might be able to contribute to patterns because I need some anyway. Excellent job anyway.

**Comment by davebaol** [comment]
Nice :+1:
