### ISSUE TITLE
ReachOrientation SteerBehavior 180º bug

### ISSUE THREAD

**Issue by Hanto** [libgdx/gdx-ai#42]
There is a issue with the way gdx ai calculates rotation, it asumes rotation values are continuous, and thats not the case with normalized angles or with the jump from 360º to 0º.(im using degrees instead of radians for ease of explanation)
When the owner is at 350º and wants to face a target that is at 10º,  instead of moving 20º degrees it reverses movement, because he doest not know that 10º is the same that 370º and just needs to move 20º, he thinks that just has to reverse the angular velocity to get to the 20º.

i fixed the problem localy using normalized angles in my rotations, and just adding 2Pi to the targetOrientation if his value was lower than owner.getOrientation() int the reachOrientation method.

**Comment by davebaol** [comment]
Which version are you referring to? This behavior has recently changed in the snapshot.

**Comment by davebaol** [comment]
I mean, PR #39 should fix your issue. 
Please, let me know if the snapshot works for you (libgdx-1.6.5-SNAPSHOT is required).

**Comment by Hanto** [comment]
You are right, i was not using the latest Version, sorry for not double checking.
But i think i found another potencial minor bug, if you dont specify an alignTolerance (default value of 0), then you will get an indeterminate form 0/0 when the owner gets aligned, because targetRotation *= rotation / rotationSize; (rotation is 0, and rotationSize is 0).
The align check should take into acount that, and check for a value minor or Equal to the alignTolerance.

**Comment by davebaol** [comment]
So you're suggesting to use `<=` [here](https://github.com/libgdx/gdx-ai/blob/master/gdx-ai/src/com/badlogic/gdx/ai/steer/behaviors/ReachOrientation.java#L86), right?

**Comment by Hanto** [comment]
yeah, that's it

**Comment by davebaol** [comment]
Ok done, thanks.
