### ISSUE TITLE
Parallel Task

### ISSUE THREAD

**Issue by piotr-j** [libgdx/gdx-ai#43]
The docs in Parallel states:
> parallel task will succeed if all the children succeed, fail if one of the children fail.

but that doesn't seem to be the case. I have this:
```
Parallel<Brain> parallel = new Parallel<>();
parallel.addChild(new TaskA());
parallel.addChild(new TaskB());		
```
I would expect parallel to stop if TaskA fails, but that doesn't happen. Is it a bug or am i misunderstanding something?
[Full example](https://github.com/piotr-j/libgdxplayground/blob/master/core/src/io/piotrjastrzebski/playground/gdxai/AIParallelTest.java)

**Comment by davebaol** [comment]
Parallel task waits until all children have finished before it will succeed or fail, see https://github.com/libgdx/gdx-ai/issues/12#issuecomment-135551857

**Comment by piotr-j** [comment]
I see. Perhaps the docs on the task could be reworded to avoid potential confusion.

**Comment by davebaol** [comment]
Read my answer on the other thread. Let's keep discussing there.
