### ISSUE TITLE
SteeringBehaviorsTest - flee test addition  and option to not wrap around display area

### ISSUE THREAD

**Issue by embee1981** [libgdx/gdx-ai#49]
Some small enhancements to the SteeringBehavioursTest suite that could be useful :-)

Would it be possible to add a test for fleeing to the SteeringBehavioursTest?

Also would it be possible to add a toggle to the behaviour of the AI actors to be able to stay within the display area (i.e. not wrap around on hitting the world bounds) and behave appropriately?)

Keep up the good work :-D

**Comment by davebaol** [comment]
I think I won't have the time for that, sorry.
PR welcome :)
