### ISSUE TITLE
DefaultIndexedGraph.getConnections could be simplified

### ISSUE THREAD

**Issue by InfectedBytes** [libgdx/gdx-ai#57]
I was looking through the pathfinding code and found this:
```java
public Array<Connection<N>> getConnections (N fromNode) {
  return nodes.get(fromNode.getIndex()).getConnections();
}
```
fromNode.getIndex returns the index into the nodes-array. So nodes.get(fromNode.getIndex()) will return the fromNode itself. Basically you could just do the following
```java
public Array<Connection<N>> getConnections (N fromNode) {
  return fromNode.getConnections();
}
```
Perhaps I overlooked something, but as it seems, the whole nodes-Array of the DefaultIndexedGraph is not really used.

**Comment by davebaol** [comment]
PR welcome :)

**Comment by davebaol** [comment]
Done! :smiley:

@InfectedBytes 
As a side note, I've added your libgdx jam game to the [gdx-ai useful links](https://github.com/libgdx/gdx-ai/wiki/Useful-Links-and-Resources).
