### ISSUE TITLE
Are there plans to improve the Wiki?

### ISSUE THREAD

**Issue by mayuso** [libgdx/gdx-ai#60]
I have used LibGDX for about a year now, I am not an expert, but I think I can say I know how to use it.
Still I can´t understand this API, I have tried MANY times, and never made it work. 

Do you guys/girls have plans to improve Wiki, or at least explain what functions the API has?
I would love to use and (one day) even help you improve this API.

**Comment by davebaol** [comment]
Well, yes, the documentation will improve over time.
However, gdx-ai covers various aspects of AI: steering behaviors, formation motion, pathfinding, behavior trees, state machines, etc...
This suggests that you should first tell us which part of the API is not clear to you. :wink:

**Comment by mayuso** [comment]
Thanks for answering so fast. 
I actually found only a couple images and some pseudo-code for the Pathfinding API and same with Behaviour Trees. That is the part I am most interested in right now. (I want to improve a couple games I have with some AI).

**Comment by davebaol** [comment]
Here are some [open source projects](https://github.com/libgdx/gdx-ai/wiki/Useful-Links-and-Resources#open-source-projects) you might be interested in.

**Comment by mayuso** [comment]
Thank you! Will take a look as soon as I get home!

**Comment by davebaol** [comment]
Nice, if you need help you can contact me on the libgdx irc channel.

**Comment by entangledloops** [comment]
With regards to the pathfinding docs, I wrote [https://github.com/libgdx/gdx-ai/wiki/A%2A](this introduction) hoping it would benefit someone like yourself.
