### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by Scellow** [libgdx/gdx-ai#79]
Hello

This library seems to be good but there are 0 examples, well there are tests but they are really confusing, it is impossible to use it, no explanation, nothing, they  mix it with scene2d stuff..

The wiki is there, but it just explain how different AI methods works, not how this library works, wich is really frustrating

Documentation seems to be huge, but you focused on explaining what are the different AIs instead of the library itself, or how to write things using your text format, wtf this is java lib, i want to use java..

For behavior trees, creating a LeafTask is easy, i extend it, ok then what? the wiki won't show me how to build an ai with transitions, conditional tasks etc, and more importantly how to actually run the tree ...

Well, first impression is Frustration

**Comment by Ali-RS** [comment]
I agree too. The explanation for behavior trees are very good but there is no standalone examples of how to use this library. I am using jMonkeyengine as my game engine and want to use this library for my game ai. After two weeks i will reach in my plan to development of my game ai system. Will really appreciate if someone put some standalone examples for using this library out of libGdx framework.

**Comment by 3xp0n3nt** [comment]
Check out https://github.com/jsjolund/GdxDemo3D. Specifically, for the dog btree mentioned in the wiki, the implementation is here: https://github.com/jsjolund/GdxDemo3D/tree/master/core/src/com/mygdx/game/objects/dog

Better than nothing!

**Comment by Ali-RS** [comment]
Okay, thanks so much, i am following those test codes and reading wiki again and again and am able to get the basic idea and how should i create and manage and use tasks in text file. It starts to be interesting.
@davebaol it would be nice if you can visit jMonkeyengine forum some times. :smiley:
