### ISSUE TITLE
New version request

### ISSUE THREAD

**Issue by mgsx-dev** [libgdx/gdx-ai#81]
Some fixes has been merged in master branch but not shipped in a release yet. Specially this commit : 
6714b6b56a86ea27394bcafa412fcf482e224b20 fixing huge issue with behavior trees. Guards are just unusable in 1.8.0.

Did you schedule a new release soon ?

**Comment by lukz** [comment]
Yeah, I was fighting with this last three hours. @mgsx-dev Thanks for pointing that bug! New release would be nice.

**Comment by Tom-Ski** [comment]
1.8.1 released today.
